{% set name = "meos" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MobilityDB/MobilityDB/archive/refs/tags/v1.1.0.tar.gz
  sha256: 912f1a94c37c2d0cdb95534a4cb127ea2bafcba767519f428417800b6a32b8e9
  patches:
    - fix_pointer_conversion_errors.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - proj
    - json-c
    - gsl
    - postgis
    - libcblas
    - libpq
    - geos
  run:
    - geos

test:
  commands:
    - test -f $PREFIX/lib/libmeos$SHLIB_EXT  # [unix]

about:
  summary: Mobility Engine, Open Source
  description: |
    MEOS (Mobility Engine, Open Source) is a C library and its associated API for manipulating temporal and 
    spatiotemporal data. It is the core component of MobilityDB, an open source geospatial trajectory data management & 
    analysis platform built on top of PostgreSQL and PostGIS.
  license: PostgreSQL
  license_file: LICENSE.txt
  home: https://www.libmeos.com/
  doc_url: https://www.libmeos.com/
  dev_url: https://github.com/MobilityDB/MobilityDB

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
