{% set name = "meos" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MobilityDB/MobilityDB/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16148e8eba25fc364ed8feb00d3359f0a6249eb0a6e7c54c53598c73b87ba391

build:
  # For win, we don't have gettext, openblas 0.3.21.* and postgis
  skip: true  # [win or s390x]
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gdal {{ libgdal }}
    - geos {{ geos }}
    - gettext
    - gsl
    - icu {{ icu }}
    - json-c
    - libpq
    - libxml2 {{ libxml2 }}
    - openblas {{ openblas }}
    - postgis
    - proj {{ proj }}
    - protobuf
  run:
    - geos {{ geos }}
    - gdal {{ libgdal }}
    - gettext
    - icu {{ icu }}
    - libxml2 {{ libxml2 }}
    - protobuf

test:
  commands:
    - test -f $PREFIX/lib/libmeos$SHLIB_EXT  # [unix]

about:
  summary: Mobility Engine, Open Source
  description: |
    MEOS (Mobility Engine, Open Source) is a C library and its associated API for manipulating temporal and 
    spatiotemporal data. It is the core component of MobilityDB, an open source geospatial trajectory data management & 
    analysis platform built on top of PostgreSQL and PostGIS.
  license: PostgreSQL
  license_family: OTHER
  license_file: LICENSE.txt
  home: https://libmeos.org
  doc_url: https://libmeos.org
  dev_url: https://github.com/MobilityDB/MobilityDB

extra:
  recipe-maintainers:
    - Diviloper
    - estebanzimanyi
